package dev.research4jar.registry

import com.fasterxml.jackson.annotation.JsonProperty
import java.io.IOException
import java.nio.ByteBuffer
import java.nio.file.Files
import java.nio.file.NoSuchFileException
import java.nio.file.Path
import java.nio.file.StandardOpenOption
import java.nio.file.attribute.PosixFilePermission
import java.nio.file.attribute.PosixFilePermissions
import java.security.MessageDigest
import java.security.SecureRandom
import java.util.EnumSet
import net.i2p.crypto.eddsa.EdDSAEngine
import net.i2p.crypto.eddsa.EdDSAPrivateKey
import net.i2p.crypto.eddsa.EdDSAPublicKey
import net.i2p.crypto.eddsa.spec.EdDSANamedCurveSpec
import net.i2p.crypto.eddsa.spec.EdDSANamedCurveTable
import net.i2p.crypto.eddsa.spec.EdDSAPrivateKeySpec
import net.i2p.crypto.eddsa.spec.EdDSAPublicKeySpec

/**
 * Registry signing keys, ported from querier/internal/registry (the keygen /
 * LoadSigningKey half of export.go). The on-disk format is Go's
 * crypto/ed25519 private key: 64 bytes — seed(32) || public key(32) —
 * hex-encoded plus a trailing newline, so keys generated by either
 * implementation are interchangeable. The i2p-crypto engine signs from the
 * 32-byte seed, which fully determines the Go key, so signatures are
 * byte-identical across implementations (Ed25519 is deterministic).
 */

internal val ED25519_SPEC: EdDSANamedCurveSpec = EdDSANamedCurveTable.getByName("Ed25519")

private const val ED25519_PRIVATE_KEY_SIZE = 64
private const val ED25519_SEED_SIZE = 32

/** What `registry keygen` prints (Go emits the same two keys, sorted). */
data class KeygenResult(
    @JsonProperty("private_key_path") val privateKeyPath: String,
    @JsonProperty("public_key") val publicKey: String,
)

/**
 * A loaded ed25519 signing key holding Go's 64-byte seed||public layout.
 */
class SigningKey internal constructor(private val raw: ByteArray) {
    private val seed: ByteArray
        get() = raw.copyOfRange(0, ED25519_SEED_SIZE)

    val publicKeyBytes: ByteArray
        get() = raw.copyOfRange(ED25519_SEED_SIZE, ED25519_PRIVATE_KEY_SIZE)

    val publicKeyHex: String
        get() = bytesToHex(publicKeyBytes)

    fun sign(data: ByteArray): ByteArray {
        val engine = EdDSAEngine(MessageDigest.getInstance(ED25519_SPEC.hashAlgorithm))
        engine.initSign(EdDSAPrivateKey(EdDSAPrivateKeySpec(seed, ED25519_SPEC)))
        return engine.signOneShot(data)
    }
}

/**
 * Creates an ed25519 keypair, writes the hex-encoded private key to
 * [keyPath] (0600), and returns the hex-encoded public key clients configure
 * for verification (Go registry.GenerateKey).
 */
fun generateKey(keyPath: Path): String {
    val seed = ByteArray(ED25519_SEED_SIZE)
    SecureRandom().nextBytes(seed)
    val privateKey = EdDSAPrivateKey(EdDSAPrivateKeySpec(seed, ED25519_SPEC))
    val publicBytes = privateKey.abyte
    keyPath.parent?.let { Files.createDirectories(it) }
    val content = bytesToHex(seed) + bytesToHex(publicBytes) + "\n"
    writeOwnerOnly(keyPath, content.toByteArray(Charsets.UTF_8))
    return bytesToHex(publicBytes)
}

/**
 * Reads a hex-encoded ed25519 private key written by [generateKey] or the Go
 * CLI (Go registry.LoadSigningKey).
 */
fun loadSigningKey(keyPath: Path): SigningKey {
    val content = try {
        Files.readAllBytes(keyPath)
    } catch (exception: NoSuchFileException) {
        // Mirror the Go os.ReadFile error text for the common miss.
        throw IOException("open $keyPath: no such file or directory")
    }
    val raw = hexToBytesOrNull(String(content, Charsets.UTF_8).trim())
    if (raw == null || raw.size != ED25519_PRIVATE_KEY_SIZE) {
        throw IllegalArgumentException(
            "signing key must be a hex-encoded 64-byte ed25519 private key",
        )
    }
    return SigningKey(raw)
}

/**
 * Go ed25519.Verify semantics: false (never a throw) for malformed keys or
 * signatures of the wrong shape.
 */
internal fun ed25519Verify(publicKey: ByteArray, message: ByteArray, signature: ByteArray): Boolean =
    try {
        val engine = EdDSAEngine(MessageDigest.getInstance(ED25519_SPEC.hashAlgorithm))
        engine.initVerify(EdDSAPublicKey(EdDSAPublicKeySpec(publicKey, ED25519_SPEC)))
        engine.verifyOneShot(message, signature)
    } catch (_: Exception) {
        false
    }

/**
 * Creates (or truncates) the file with owner-only permissions like Go's
 * os.WriteFile(..., 0o600). Falls back to default permissions on filesystems
 * without POSIX attributes (Windows), matching Go's behavior there.
 */
private fun writeOwnerOnly(path: Path, content: ByteArray) {
    try {
        val ownerOnly = PosixFilePermissions.asFileAttribute(
            EnumSet.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE),
        )
        Files.newByteChannel(
            path,
            setOf(
                StandardOpenOption.CREATE,
                StandardOpenOption.WRITE,
                StandardOpenOption.TRUNCATE_EXISTING,
            ),
            ownerOnly,
        ).use { channel ->
            val buffer = ByteBuffer.wrap(content)
            while (buffer.hasRemaining()) {
                channel.write(buffer)
            }
        }
    } catch (_: UnsupportedOperationException) {
        Files.write(path, content)
    }
}
